# Tomcat
server:
  port: 8090

# Spring
spring:
  application:
    # 应用名称
    name: epsilon-system-server
  profiles:
    # 环境配置
    active: dev
  cloud:
    nacos:
      discovery:
        namespace: 6fccce6e-20e4-4235-9080-01bd86f1430c
        group: DEFAULT_GROUP
        server-addr: 192.168.0.101:8848
      config:
        # 配置所属命名空间的id
        namespace: ${spring.cloud.nacos.discovery.namespace}
        group: ${spring.cloud.nacos.discovery.group}
        # 后缀名
        file-extension: yaml
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        # 配置自动刷新
        refresh-enabled: true
        # 启用远程同步配置
        enable-remote-sync-config: true
  config:
    import:
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/epsilon_open_platform?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: 192.168.0.102
      port: 6379
      password: redis
      database: 0
      lettuce:
        pool:
          enabled: true
          max-idle: 16
          max-active: 32
          min-idle: 8

# Mybatis-plus
mybatis-plus:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 主键自动递增
      id-type: auto
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0